cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name:


application2:
  bucket:
    name:

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 4MB
      max-file-size: 10MB
      max-request-size: 20MB

  #Exclude Aws RegionProviderAutoConfiguration
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration

#server:
#  port: 9090

  cloud:
    function:
      scan:
        packages: com.microd.imagegenerator

